### ISSUE TITLE
native implementation mistaken for header

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-spec#1443] opened 2015-10-18 19:42 UTC
This type checks:

```ceylon
class NC2() {
    native("jvm") shared void foo() => print("impl 1");
    native("jvm") shared void foo() => print("impl 2");
}
```
but, should have:

1. "Native member does not implement any header member: foo in NC2"
2. "Duplicate native implementation: foo"

**Comment by quintesse** [comment] 2015-10-18 23:21
Can't reproduce this, I get:

```
./source/test/test.ceylon:8: error: foo() is already defined in NC2
    native("jvm") shared void foo() => print("impl 2");
```

**Comment by jvasileff** [comment] 2015-10-19 00:16
Oh, right, this is actually much more nuanced.

1. In Eclipse, with *just* "compile to project to JS", no error is produced for the original example.
2. Same as above, but with one of the declarations removed, an error is produced.
3. At the CLI, `ceylon compile-js` produces no error regardless of how many `native("jvm")` declarations exist.
4. If instead, we use `native("js")`, `ceylon compile` produces an error for one declaration, not with two or more.

**Comment by quintesse** [comment] 2015-10-19 01:53
1. and 3. are basically the same thing and is something specific for the JS backend: it just ignores all errors in code marked for the JVM.
The other two are also a single issue really, which is that no dups are detected if there's no header.

**Comment by quintesse** [comment] 2015-10-19 01:54
The duplicates should now generate proper errors.

**Comment by quintesse** [comment] 2015-10-20 10:41
Will close this issue because what's described has been fixed.

**Closed by quintesse** 2015-10-20 10:41 UTC
Labels: bug, high priority
