### ISSUE TITLE
Error on typechecker version imports

### ISSUE THREAD

**Issue by lucaswerkmeister** [ceylon/ceylon-spec#1147] opened 2014-11-22 15:26 UTC
```sh
cd /tmp
git clone https://github.com/ceylon/ceylon.ast.git
cd ceylon.ast
git checkout a3ae7c398145ff34c0a81282a04e3aab7731b887
ceylon compile
```
> This is a type checker bug, please report. 
Expecting to add error on non present module node: Module[default, unversioned]. Error module (transitively) imports conflicting versions of dependency 'com.redhat.ceylon.typechecker': version '1.1.0' and version '1.1.1'
source/ceylon/ast/redhat/module.ceylon:21: error: module (transitively) imports conflicting versions of dependency 'com.redhat.ceylon.typechecker': version '1.1.0' and version '1.1.1'
```ceylon
module ceylon.ast.redhat "1.1.0" {
      ^
```
> source/ceylon/ast/redhat/module.ceylon:21: error: module (transitively) imports conflicting versions of dependency 'com.redhat.ceylon.typechecker': version '1.1.0' and version '1.1.1'
```ceylon
module ceylon.ast.redhat "1.1.0" {
      ^
```
> […]

The same error occurs a total of 66 times, across the different modules.

I see two bugs:
- “Expecting to add error on non present module node”
- The error should probably occur at most once per module

**Comment by gavinking** [comment] 2015-04-24 17:16
@lucaswerkmeister I'm closing this, because it's not a bug in the typechecker, and because I don't really know what it's about.

**Closed by gavinking** 2015-04-24 17:16 UTC

**Comment by lucaswerkmeister** [comment] 2015-04-24 17:24
That’s a very weird phrasing of “can no longer reproduce”… fine :)

**Comment by jvasileff** [comment] 2015-04-24 17:38
@lucaswerkmeister it looks like you may get the imports of the language module as `shared` imports, for free!

```xml
    <dependencies>
        <module name="com.redhat.ceylon.compiler.java" slot="1.1.1"/>
        <module name="com.redhat.ceylon.compiler.js" slot="1.1.1"/>
        <module name="com.redhat.ceylon.common" slot="1.1.1"/>
        <module name="com.redhat.ceylon.module-resolver" slot="1.1.1"/>
        <module name="com.redhat.ceylon.typechecker" slot="1.1.1"/>
        <module name="org.jboss.modules" slot="1.3.3.Final"/>
        <module name="org.jboss.jandex" slot="1.0.3.Final"/>
    </dependencies>
```

I'm basing this on 1) the conflict error messages, and 2) you don't need a module import to do:

```ceylon
import com.redhat.ceylon.compiler.typechecker {
    TypeChecker
}
```
