### ISSUE TITLE
Wrong type parameter captured for member anonymous object and default type parameter 

### ISSUE THREAD

**Issue by sgalles** [ceylon/ceylon-spec#1299] opened 2015-05-14 21:38 UTC
This code should not compile (and actually it does not compile if `Foo` is top level)
```ceylon
shared void run(){ // keep this method
    class Foo<Bar=String>(){ 
        shared object b {
            shared variable Bar? c = null;
        }
    }
    Foo<Float>().b.c = "aaa";
}
```

**Comment by gavinking** [comment] 2015-05-14 23:26
Grrrrr `TypeParameter.hashCode()` is broken, it seems.

**Comment by gavinking** [comment] 2015-05-14 23:36
So the issue is caused by @FroMage's qualifier stuff. Since the qualifier is set after `DeclarationVisitor` has already run, the `hashCode()` of the nested `TypeParameter` changes after the type of the `Value` has already been set.

**Comment by gavinking** [comment] 2015-05-15 00:08
So I have "fixed" it, though the fix feels a little fragile...

**Comment by gavinking** [comment] 2015-05-15 00:14
Closing, thanks for the bug report @sgalles.

**Closed by gavinking** 2015-05-15 00:14 UTC
