### ISSUE TITLE
Type inference bug

### ISSUE THREAD

**Issue by renatoathaydes** [ceylon/ceylon-spec#1302] opened 2015-05-17 20:45 UTC
In the following code, the wrong type is inferred in the last call, and this does not compile:

```ceylon
class X<out Y>(shared Y y) {}
X<To> transform<From, To>(X<From> x, To(From) convert)
        => X(convert(x.y));

X<String> x1 = X("10");
X<Integer?> x2 = transform(x1, parseInteger); // Error
```

The error is on `parseInteger`:

```
Argument must be assignable to parameter convert of transform: Integer?(String, Integer=) is not assignable to Integer?(String|Integer)
```

But there is no way that `From` could be an `Integer` in the above code.

If the type parameters are explicitly given, it compiles:

```ceylon
X<Integer?> x2 = transform<String, Integer?>(x1, parseInteger); // OK
```

**Comment by renatoathaydes** [comment] 2015-05-17 20:45
Moved from https://github.com/ceylon/ceylon.language/issues/683

**Comment by renatoathaydes** [comment] 2015-05-17 20:47
If the parameter `Y` is made non-covariant, then the error gets worse with both the argument `x1` and the function `parseInteger` giving errors in the last line.

**Comment by gavinking** [comment] 2015-05-18 00:04
OK, so this one is a little unfortunate. It's not a _bug_, precisely, in the sense that the typechecker is behaving exactly as expected according to the rules in §3.6.5.

The issue is that the parameter type here is `To(*Tuple<From,From,[]>)` and the argument type is `Integer?(*Tuple<String|Integer,String,[]|[Integer]>)`, so you can see there that `String|Integer` actually _is_ being assigned to `From`.

The only fixes for this&mdash;while easy enough to implement&mdash;would be pretty nasty and adhoc (always ignore the first type parameter in a `Tuple`?) and so I'm not sure that fixing this is worthwhile. You can always write any one of these three options:

```ceylon
    X<Integer?> x2 = transform(x1, 
        parseInteger of Integer?(String));

    X<Integer?> x3 = transform(x1, 
        (String s) => parseInteger(s));

    X<Integer?> x4 = transform<String,Integer?>
            (x1, parseInteger);
```

**Comment by sadmac7000** [comment] 2015-05-18 00:49
It seems we should somehow be able to turn
```
Tuple<String|Integer,String,[]|[Integer]>
```

In to
```
Tuple<String,String,[]>|Tuple<String|Integer,String,[Integer]>
```

**Comment by gavinking** [comment] 2015-05-18 01:30
@sadmac7000 that would not solve the problem.

**Comment by sadmac7000** [comment] 2015-05-18 01:32
Hmm.

Function argument tuples are contravariant, correct? So a supertype should be assignable to them.

**Comment by gavinking** [comment] 2015-05-18 01:44
The issue is about type argument inference. Not subtyping.

**Comment by sadmac7000** [comment] 2015-05-18 01:49
Ah. I think I see. Right, it's assuming From = String|Integer

**Comment by sadmac7000** [comment] 2015-05-18 01:52
Well, one patch would be to deconstruct as I mentioned on the way in to type inference, run inference with each type singly, then set the result to the intersection of each individual inference.

**Comment by jvasileff** [comment] 2015-05-18 04:51
It seems like an `out` hint on `From` would help, since it would push `convert`'s `From` to `Nothing`, with `x`'s `From` giving us `String`. And it does work. But isn't `out` the default?

Although, an `in` hint *also* works??? Is the `in` algorithm doing a better job of taking into account all of the constraints, including `Tuple.First` for the `Callable`'s `Arguments`?

Shorter reproductions:
```ceylon
void f<T>(Anything(T) g) {}
f(parseInteger);

class InBox2<in T, in U>() {}
void func<V>(V t, InBox2<V, V> b) {}
func("", nothing of InBox2<String|Integer, String>);
```

My other idea is a bit crazier: standardize on `Anything` for `Tuple.Element` for `Callable.Arguments`, at all levels of nesting. In fact, this is something I wanted once before. By using the canonical form for argument tuples, `Callable`s are asking for more than they actually need.

An even crazier idea would be to have `Tuple` satisfy a `NonIterableTuple<First, Rest>` interface, and use that for `Callable`s.

**Comment by gavinking** [comment] 2015-05-18 07:02
> Although, an `in` hint *also* works??? 

Ahyes, of course. That's the right solution, as we can see if we write the thing in curried form:

```ceylon
class X<out Y>(shared Y y) {}

X<To> transform<in From, out To>
        (To(From) convert)(X<From> x)
        => X(convert(x.y));

X<String> x1 = X("10");
X<Integer?> x3 = transform(parseInteger)(x1); //No error
```

> It seems like an `out` hint on `From` would help, since it would push `convert`'s `From` to `Nothing`, with `x`'s `From` giving us `String`. And it does work. But isn't `out` the default?

Um. Wait. Let me check the spec. Perhaps there is some difference. I must admit it's a surprise to me that this would change the behavior.

**Comment by gavinking** [comment] 2015-05-18 07:19
> Let me check the spec.

I don't see anything obvious in the spec for this stuff, but I do have an explanation for the difference in behavior: `ExpressionVisitor:3985-3987`. It does something for covariant type parameters that it doesn't do for invariant type parameters. It's unclear to me if this is:

1. a bug,
2. an unspecified feature, or
3. something that is actually consistent with the spec but non-obvious from the text of the spec.

Investigating.

**Comment by gavinking** [comment] 2015-05-18 07:21
A couple of experiments convince me that this is a feature not a bug. But is it blessed by the spec?

**Comment by gavinking** [comment] 2015-05-18 07:35
This suspicious code was part of the implementation of #763.

And note that there is a difference between @RossTate's original statement of #763&mdash;which is what the typechecker implements&mdash;and what I wrote down in the spec.

So the question remains: is it a feature or a bug. This issue suggests it is a bug, and that the spec is right.

**Comment by gavinking** [comment] 2015-05-18 07:44
OK, so after seeing how many tests would be broken by changing that code to give the exact same behavior for the invariant and covariant cases, I now conclude that it is a feature, and the spec needs to be adjusted to document this difference.

Anyway, thanks to @jvasileff, we already have our solution to @renatoathaydes's problem.

**Comment by RossTate** [comment] 2015-05-18 14:48
I'm pretty sure this is a bug.

1. For `X<String>` to be a subtype of `X<From>`, `From` must be a supertype of `String`.
2. For `Integer?(*Tuple<String|Integer,String,[]|[Integer]>)` to be a subtype of `To(*Tuple<From,From,[]>)`, `To` must be a supertype of `Integer?` and `From` must be a subtype of `String|Integer` and of `String`.
3. This gives us that `String <: From <: String&<String|Integer>` must hold, and `String&<String|Integer>` is equivalent to `String`, so `From` should be inferred to be `String` no matter what strategy you use.
4. The return type is covariant with respect to `To`, and we have that `Integer? <: To` must hold, so `To` should be inferred to be `Integer?`.

Did I screw up my reasoning?

**Comment by gavinking** [comment] 2015-05-18 16:33
@RossTate the issue is that we treat invariant type parameters _very nearly_ (but not quite) as if they were covariant type parameters. In this case we have something that is by rights contravariant but it's not explicitly marked as such. Marking it contravariant fixes the problem.

> `To` must be a supertype of `Integer?` and `From` must be a subtype of `String|Integer` __and__ of `String`.

You're assuming facts not in evidence ;-) That is what happens _if_ we know that `From` is contravariant. In this case it's being treated as if it were covariant, so the reasoning is:

> `To` must be a supertype of `Integer?` and `From` must be a subtype of `String|Integer` __or__ of `String`.

**Comment by RossTate** [comment] 2015-05-18 17:09
The reasoning I laid out for `From` is completely independent of its variance. Do you mean to say that you don't recognize that `Callable` is contravariant with respect to its input type?

**Comment by gavinking** [comment] 2015-05-18 17:22
It is the variance of type parameter being inferred that determines if we look for a lower bound or an upper bound. The variance of the parameter of Callable affects that but it is not the only thing that does.

Again, the algorithm can fail for invariant type parameters, since the problem is over constrained so we just do the best we can according to very simple rules.

**Comment by RossTate** [comment] 2015-05-18 17:26
But both the upper bound and the lower bound on `From` are `String`, so that doesn't explain anything.

**Comment by gavinking** [comment] 2015-05-18 17:29
PS I get what you're saying here: that in the invariant case we get a set of lower bounds and upper bounds depending on the location in the parameter list that the type parameter occurs. (Unlike in the case of covariance where we get only lower bounds and contravariance where we get only upper bounds.)

I suppose we could consider taking both bounds into account if they're not conflicting. I guess the rules don't need to be -that- complicated.

**Comment by gavinking** [comment] 2015-05-18 17:30
Right now we never compute two bounds. On the theory that we might no what to do with them.

**Comment by RossTate** [comment] 2015-05-18 17:34
We're speaking past each other, so how about this: explain how you come to the error step by step, in the same way I explained how I get the correct result regardless of whether you use only the upper bounds or only the lower bounds. Then I can look through each step and either understand why you are right in getting the error or understand how exactly you are wrongly getting the error.

**Comment by gavinking** [comment] 2015-05-18 17:39
The issue is that we are treating something that you would say is an upper bound as a lower bound. This almost always works I practice, but not in this case.

**Comment by RossTate** [comment] 2015-05-18 17:43
Is there any good reason why? That can only get you worse results.

**Comment by gavinking** [comment] 2015-05-18 17:49
Well, because it's simpler, and almost always works.

Look I'm on my phone right now but I will take a closer look later at whether I can come up with something reasonably predictable that computes two bounds and then throws one or the other away. It's probably doable but I need to see the code and have the spec in front of me.

**Comment by renatoathaydes** [comment] 2015-05-18 18:48
@gavinking  wrote:
>  In this case we have something that is by rights contravariant but it's not explicitly marked as such. Marking it contravariant fixes the problem.

I think you mean **covariant**, not contravariant, given that what fixed the function signature was marking `From` with the `out` tag.

Anyway, shouldn't the same principle, then, be used to make `Iterable.map`'s type parameter (and many other similar functions in the Ceylon language module) covariant?
I see no function's type parameters in the Ceylon language module marked as covariant or contravariant.

Can you show me an example not involving type inference where it would be useful to mark function type parameters as `in` or `out` (I just want to learn, hope the question does not sound confronting)?

**Comment by gavinking** [comment] 2015-05-18 19:29
> I think you mean **covariant**, not contravariant, given that what fixed the function signature was marking `From` with the `out` tag.

No. As I said above, the correct fix is to mark it `in`. It is conceptually _contravariant_.

> Anyway, shouldn't the same principle, then, be used to make `Iterable.map`'s type parameter (and many other similar functions in the Ceylon language module) covariant?

Well no. The type parameter of `map()` is conceptually covariant, so the default strategy works just fine. This passes the typechecker:

```ceylon
{Integer?+} result = {"hello", "world"}.map(parseInteger);
```

> Can you show me an example not involving type inference where it would be useful to mark function type parameters as `in` or `out` (I just want to learn, hope the question does not sound confronting)?

No. There is no case. It is _purely_ a hint to type inference. And it is only `in` that we typically ever need (as in this case). It's basically never necessary to explicitly mark a function type parameter `out`. At least, that has been the case up until now.

What I'm not sure about is: if we fix this "bug", which only affects a tiny tiny number of usecase, will that mean that the default behavior is worse for conceptually covariant type parameters, forcing us to use an explicit `out` annotation much more frequently.

I'm not sure.

**Comment by jvasileff** [comment] 2015-05-18 19:55
I don't follow that. It seems that from a conceptual standpoint:

With `out`, the type parameter `From` wants to be `Nothing`. That works great for the callable. But the `x` argument pulls it up to `String` (which is still fine for the callable).

With `in`, the type parameter `From` wants to be `Anything`. That works great for `x` since a `String` is an `Anything`. But it's no good for the callable, which can't accept `Anything`s. So with the **two** constraints imposed by the `Callable`, it gets pulled back down to `String` (which is still fine for `x`).

Both work here, which makes sense to me. What doesn't quite make sense to me is why a hint is needed at all.

FWIW, it appears to make no difference if the two contravariant uses of the type parameter are within the same argument or two separate arguments:

```ceylon
    class InBox1<in T>() {}
    void func1<V>(InBox1<V> b1, InBox1<V> b2) {}
    func1(nothing of InBox1<String|Integer>, nothing of InBox1<String>);

    class InBox2<in T, in U>() {}
    void func<V>(InBox2<V, V> b2) {}
    func(nothing of InBox2<String|Integer, String>);
```

**Comment by RossTate** [comment] 2015-05-18 21:03
@jvasileff hits upon the same thing you're saying that I'm confused by. You keep talking about `in` versus `out` annotations serving as hints to inference. Those hints are relevant elsewhere, but not here. So I'm wondering if you understand the source of the problem. But you're on your phone, so just wait until you've had a chance to sit a proper computer, heheh.

**Comment by gavinking** [comment] 2015-05-18 21:17
> Those hints are relevant elsewhere, but not here.

That's just not right.

Consider:

```ceylon
interface Something<T> { ... }

Something<T> something<T>(Something<T> s1, Something<T> s2) => .... ; 

Something<Foo> sfoo = ... ;
Something<Bar> sbar = ... ;

value result = `Something<Foo&Bar>`(sfoo, sbar);
```

Now, _without knowing anything more about the semantics of `Something` and `mutable()`_, how are you going to tell me if I should infer `Something<Foo&Bar>` or `Something<Foo|Bar>` here?

You can't. You need some extra information. There are cases where `&` is appropriate, and other cases where `|` is appropriate. (The `|` case is more common, since that is what you want for e.g. `MutableList`s.)

**Comment by RossTate** [comment] 2015-05-18 21:21
Uh, you should get an error (assuming you meant `Something` to be invariant).

But that doesn't matter here. I said the hints *are* relevant elsewhere; just not here.

**Comment by gavinking** [comment] 2015-05-18 21:24
> Uh, you should get an error (assuming you meant `Something` to be invariant).

Why?

**Comment by gavinking** [comment] 2015-05-19 00:19
So I have implemented what I believe Ross is getting at in @2b04d8f, and it does appear to correct this corner case without affecting much else&mdash;except one test I had which was very similar to to this case.

But what I don't like is [this rule](https://github.com/ceylon/ceylon-spec/commit/2b04d8f2deb07a5beb23f6df39dd74a1f07e9d3e#diff-047987a3b9186a4040dd3aa3c8ce93f5R3705) for picking between the upper and lower bounds. I can't find any particularly good justification for it, nor do I even really know if it's correct or not.

**Comment by RossTate** [comment] 2015-05-19 00:58
>> Uh, you should get an error (assuming you meant Something to be invariant).
> Why?

Because `Something<Foo>` is not a subtype of either `Something<Foo&Bar>` or `Something<Foo|Bar>`. Unless `Foo` and `Bar` are equivalent types, there is no valid type argument for that call.

> But what I don't like is this rule for picking between the upper and lower bounds. I can't find any particularly good justification for it, nor do I even really know if it's correct or not.

Ah, I agree that there's no justification for your implementation of `pickBound`. Here's what you should do. If the return type is covariant with respect to that type variable, then you should use the lower bound, and if it's contravariant then you should use the upper bound. The justification is that this result in the most precise return type possible. In other words, any other type argument you could use that variable would result in a strictly less useful return type. This doesn't suggest what to do for invariant type variables. And for bivariant/independent type variables (such as `From` in this example), it doesn't matter which you do (reification aside); so long as the lower bound is a subtype of the upper bound then any type argument in that range would be valid and would result in the same return type.

Right now, if you instead wanted to be consistent with what you had been doing, then you would have `pickBound` pick the lower bound unless the type variable had been annotated with `in`. Because that doesn't matter for bivariant/independent type variables like `From` in this example, that would still work for this example and would keep everything else like it had been before.

Since you're recompiling everything anyways at the moment, here's an experiment worth running. I'd be interested to learn what happens if you made `pickBound` fail if the type variable occurs invariantly and the lower bound and upper bound are not equivalent. I've seen a number of errors reported due to incorrectly guessing in this situation, but I don't know how much type checked code relies on guessing here.

**Comment by gavinking** [comment] 2015-05-19 01:11
> Because `Something<Foo>` is not a subtype of either `Something<Foo&Bar>` or `Something<Foo|Bar>`. Unless `Foo` and `Bar` are equivalent types, there is no valid type argument for that call.

I don't see how that can possibly be right. We have plenty of examples like `Array` and `ArrayList` and `HashMap` which prove that, from a practical point of view, it _does_ make sense to choose a union of argument types even for an invariant return type.

> Ah, I agree that there's no justification for your implementation of `pickBound`.

Right, but nor, AFAICT, is there any other especially better implementation of `pickBound()` that would give me better results in practice. This implementation does seem to give _extremely_ good results on all the examples I have.

>  Here's what you should do. If the return type is covariant with respect to that type variable, then you should use the lower bound, and if it's contravariant then you should use the upper bound.

Well OK so you're saying essentially the exact same thing that I've been saying the whole time, it's just that you think we should determine the variance of a type parameter _implicitly_ by inspecting the schema of the function, whereas I think that's totally inconsistent with what we do for classes and other type schemas where the variance of a type parameter is always _explicit_.

**Comment by gavinking** [comment] 2015-05-19 01:12
> I've seen a number of errors reported due to incorrectly guessing in this situation, but I don't know how much type checked code relies on guessing here.

The corner cases where inference fails are tiny in number compared to the cases where it does the right thing. Almost any other implementation of `pickBound()` here causes a whole bunch of tests to fail.

**Comment by RossTate** [comment] 2015-05-19 01:23
>> Because `Something<Foo>` is not a subtype of either `Something<Foo&Bar>` or `Something<Foo|Bar>`. Unless `Foo` and `Bar` are equivalent types, there is no valid type argument for that call.
>
> I don't see how that can possibly be right. We have plenty of examples like `Array` and `ArrayList` and `HashMap` which prove that, from a practical point of view, it _does_ make sense to choose a union of argument types even for an invariant return type.

I can see other examples where that is true, but not the one you gave here. `something`'s inputs are *invariant* wrt `T`, so it would be unsound to accept that code. If they were *covariant* wrt `T`, that would be a different story (even keeping the output invariant wrt `T`).

**Comment by gavinking** [comment] 2015-05-19 01:41
```ceylon
MutableList<T> join<T>(MutableList<T> list1, MutableList<T> list2) {
    value list = ArrayList<T>();
    list.addAll(list1);
    list.addAll(list2);
    return list;
}

MutableList<Foo> fooList = ... ; 
MutableList<Bar> barList = ... ;
MutableList<Foo|Bar> = join(fooList, barList);
``` 

Nothing unsound about that.

**Comment by gavinking** [comment] 2015-05-19 01:45
Oh, sorry, sure, yeah, ok, bad example. Imagine that they're plain `List`s as the inputs.

**Comment by gavinking** [comment] 2015-05-19 01:49
OK, so here's a much better example, that actually does pass the typechecker:

```ceylon
MutableList<U|V> join<U,V>(MutableList<U> list1, MutableList<V> list2) {
    value list = ArrayList<U|V>();
    list.addAll(list1);
    list.addAll(list2);
    return list;
}

MutableList<Foo> fooList = ArrayList<Foo>(); 
MutableList<Bar> barList = ArrayList<Bar>();
MutableList<Foo|Bar> result = join(fooList, barList);
```

**Comment by gavinking** [comment] 2015-05-19 01:55
Well, that doesn't really demonstrate my point either. It's 4AM here. Brain shutting down.

**Comment by gavinking** [comment] 2015-05-19 07:29
OK, I have slept and can probably express coherent thoughts again. So to recap: we still have a situation where the algorithm for covariant and contravariant type parameters is exactly right, but for the invariant case we do something ad hoc. _Both_ versions of the algorithm had something a bit nasty buried in them, but I would say the nasty thing buried in the new version (`pickBound()`) is actually the more nastier of the two, though it seems to result in better behavior for a very small number of corner cases.

Again: what we have works perfectly great if you are able to explicitly make a type parameter as `in` or `out`, sidestepping the nastiness.

So what @RossTate's argument boils down to is this: we should&mdash;only in the case of a generic _function_, but not for _classes_&mdash;actually _infer_ the variance of a type parameter by looking at how it occurs in the return type. This would relieve the developer of having to add an explicit `in` or `out` annotation in certain cases.

I don't think that's a bad idea, and it might further improve things, but it still leaves me with lots of cases where I *still* don't know what to do: what about for invariant classes like `ArrayList()`? what about if the type parameter never even occurs in the return type, which is the case here? I would still need a tie breaker in these cases, and I guess the tie breaker would be to use the algorithm for _covariant_ type parameters. I'm not sure how will it will work in practice but I'm willing to give it a try.

**Comment by gavinking** [comment] 2015-05-19 11:41
I have implemented this, and it does seem to be an improvement, on balance. Still need to write a spec!

**Comment by renatoathaydes** [comment] 2015-05-19 20:12
Wow, glad my small example led to such a lengthy discussion on type theory :)

But I think it's important this gets a good solution as this kind of function is very common, I would suggest, in Ceylon functional code.

And sorry Gavin about my previous comment, I see that you had it right with the contravariant argument... I was also writing late at night, you know.....

**Comment by jvasileff** [comment] 2015-05-19 20:20
Based on the idea that (pre-patch), inference in the presence of `in` or `out` hints worked perfectly, I believe the notes below make sense. The hints should be easily inferred, when they even matter (which they don't in Renato's case, I think that's just a bug). I'm of course taking for granted that the rest of the impl/bounds checking/whatever "just works", as it seems to for non-invariant cases.

Inferring variance hints:

* To state the obvious: consumers of `Anything` are the most “valuable” types of consumers, and producers of `Nothing` are the most “valuable” types of producers.
* Both caller’s and callee’s generally want the most valuable types. But these goals can be at odds. When in conflict, the caller should win.
* Therefore, simply:
  * If the type parameter appears in the return:
    * If the parameter is in a covariant position in the return type, `out` should be inferred (prefer `Nothing`).
    * If the parameter is in a contravariant position in the return type, `in` should be inferred (prefer `Anything`).
    * If both, default to `out`, as it is generally what we want (e.g. a return of `MutableList<T>`)
  * Otherwise, if the type parameter appears in the argument list:
    * If the parameter is in a covariant position in the argument list, `out` should be inferred (prefer `Nothing`)
    * If the parameter is in a contravariant position in the argument list, `in` should be inferred (prefer `Anything`)
    * If both, default to `out`, as it is generally what we want.

Given that constructors don't have a return type in the same sense that functions do, the above will be performed as if they return void. Of course, explicit annotations always rule.

Note: so long as inference is performed in the case of invariant/over defined situations, discontinuities are unavoidable. The question is only as to the direction of the discontinuity—if a discontinuity happens due to the addition of a contravariant argument or a covariant argument.

The above rules for curry results in the correct:

    Return(*Rest) curry<out Return, in Argument, in First, in Rest>

because `Argument`, `First`, and `Rest` are all contravariant in the argument list.

For TreeSet, the result is the reasonable and consistent:

    TreeSet<Object> x = TreeSet((Object x,Object y)=>…) // “in” T
    TreeSet<Integer> x = TreeSet((Integer x,Integer y)=>…) // “in” T
    TreeSet<Integer|String> x = TreeSet((Object x,Object y)=>…, “hello”, 1) // “out” T

The only thing that is really *subjective* here is preferring the covariant approach for invariant parameters. But this seems to work very well, and is much more convenient than not performing inference at all in the invariant case.

**Comment by jvasileff** [comment] 2015-05-20 06:31
The notes above cheated with `TreeSet` by pretending constructors return void, which of course won't work. But, everything works out with the very small adjustment of being less sure of invariant type parameters, as follows:

1. If the type parameter is explicitly `in` or `out`, go with that. Otherwise,
2. If the return type is covariant or contravariant in the type parameter, go with that. Otherwise,
3. If the arguments are covariant or contravariant in the type parameter, go with that. Otherwise, 
4. Default to `out`. 

Defaulted parameters that are not used should be disregarded (e.g. `TreeSet` with only `compare`.)

The is very simple and intuitive (go for the most useful type for *someone*, otherwise fallback to `out`), and it works well.

I'd be *very* interested to hear any reasons why this won't work.

**Comment by RossTate** [comment] 2015-05-20 18:09
Well, that's still underspecified. Consider the following:

```
class Reference<in Input, out Output>(Input init) given Input satisfies Output {...}
```

According to your specification `Reference("Hello")` would result in either `Reference<String, String>` or `Reference<Anything, Anything>` depending on whether you inferred `Input` first (resulting in the former) or `Output` first (resulting in the latter).

**Comment by jvasileff** [comment] 2015-05-20 18:19
The notes above don't apply in that example - you are explicitly specifying `in` and `out`. In other words, this strategy doesn't address what happens *after* you've determined the preferred variance.

**Comment by RossTate** [comment] 2015-05-20 18:21
Hence "underspecified". In other words, those rules aren't enough for a programmer to predict what the result will be.

**Comment by jvasileff** [comment] 2015-05-20 18:41
Ok, right, makes sense. But the strategy does at least seem sufficient to replace the previous approach towards invariant parameters that broke in Renato's example. And it does so in a way that preserves the benefits of the previous approach (e.g. handling of `TreeSet`).

Handling the `Reference` case too would be a nice addition.

**Comment by gavinking** [comment] 2015-05-20 23:07
Alright, so the winner of this issue was @jvasileff. His strategy seems robust. I need to write a spec for it. But anyway it was a team effort. Thanks @RossTate.

**Comment by RossTate** [comment] 2015-05-22 21:29
So what's plan for clarifying the behavior for `Reference`? Always infer left to right?

**Comment by gavinking** [comment] 2015-05-22 22:15
@RossTate It infers `Anything` in both cases. No, it's nothing to to with LTR ordering, it's just that it applies the constraints as a separate step.

**Comment by gavinking** [comment] 2015-05-22 22:19
Excuse me, that's not the correct explanation. The real reason is that it ignores inferred args for other type parameters when applying the constraint. But actually I was going to look into changing that. It was already on my todo list.

**Comment by gavinking** [comment] 2015-05-22 22:19
There's a TODO at ExpressionVisitor.java:4261.

**Comment by RossTate** [comment] 2015-05-23 16:10
?

1. `Input` becomes intersection of its upper bounds, which in this case is `Output`
2. `Output becomes union of its lower bounds, which in this case is either `String` (if you realize that the parameter now has type `Output`) or `Nothing` (if you don't realize that)

or

1. `Output` becomes union of its lower bounds, which in this case is `Input`
2. `Input` becomes intersection of its upper bounds, which in this case is `Anything` because it has no upper bounds by this point

So you get either `Reference<String, String>` or `Reference<Nothing, Nothing>` (which is broken) or `Reference<Anything, Anything>` depending on in which order you infer. What am I misunderstanding here?

**Comment by gavinking** [comment] 2015-05-23 17:42
@RossTate Well, it infers `Reference<Anything,String>` because `Input` in contravariant, so the occurrence of `String` in a _covariant_ location of the parameter list does not constraint it. On the other hand, this covariant occurrence of `Input`, which has `Output` as a supertype, _does_ push `Output` upward, because `Output` is _covariant_. Thus far it's all quite sound.

What I need to look into, like I said above, is then coming back and substituting `Output=String` when I apply the upper bound on `Input` to the inferred value for `Input`. Right now the upper bound gets thrown away.

**Comment by RossTate** [comment] 2015-05-23 19:28
`Anything` is not a subtype of `String`, so isn't that unsound.

**Comment by gavinking** [comment] 2015-05-23 19:31
Huh? The inferred types are rejected of course.

**Comment by RossTate** [comment] 2015-05-24 00:16
Ah, so you're opting to error even if there are possible solutions. I misunderstood that.

**Comment by gavinking** [comment] 2015-05-24 23:26
I have updated the spec to cover the outcome of this discussion. I still need to circle back around to the issue of upper bounds and type inference, which is on my todo list.

Thanks everyone!

**Closed by gavinking** 2015-05-24 23:26 UTC
Labels: bug
