### ISSUE TITLE
xplatform module with missing native impls

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-spec#1423] opened 2015-09-15 06:44 UTC
I have a project in the IDE that is being compiled for both backends. It has this module:

```ceylon
module nat "1.0.0" {}
```

In the root package it has this unit:

```ceylon
native
shared void run();

native("jvm")
shared void run() {}
```

I don't get any error for the missing `"js"` implementation.

Note that _sometimes_ I get the opposite result: leaving out the `"jvm"` implementation results in no errors.

@quintesse would you take a look at this please.

**Comment by quintesse** [comment] 2015-09-30 14:48
I just tested this and it *seems* to work just fine here. Let me test some more.

**Comment by quintesse** [comment] 2015-09-30 14:54
Ok, reproduced it.
Btw, just as a remark, the typechecker itself will not be able to detect this, only the JS compiler itself.
This is because the JS backend has this special way of mixing manually written JS files with Ceylon that the typechecker doesn't know anything about.

**Comment by quintesse** [comment] 2015-09-30 14:55
Oh just great, the JS compiler doesn't even complain about this code!

**Comment by quintesse** [comment] 2015-10-11 21:16
Ok, I can close this now, unfortunately now the problem described in ceylon/ceylon-js#637 is back again. Only I have no idea how. Setting a breakpoint on the code that adds the error shows that each one is only added once.

**Closed by quintesse** 2015-10-11 21:16 UTC
Labels: bug, high priority
