### ISSUE TITLE
over-aggressive simplification to homogenous Tuple type

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-spec#1440] opened 2015-10-13 16:53 UTC
I don't know if this affects actual type checking, but the type inference information available in error messages and IDE mouseovers incorrectly simplifies `Tuple` intersections with `Sequential` to canonical, homogeneous `Tuple`s, disregarding `Tuple`'s type parameters that are not present in `Sequential`.

The mouseover on `value` for:
```ceylon
value seq = (nothing of <String|Integer>[2] & Integer[]);
```
is "Inferred type `Integer[2]`"

And the error message for:
```ceylon
value seq = (nothing of <String|Integer>[2] & Integer[]);
Integer[2] seq2 = seq;
```
*sometimes* says "`Integer[2]` is not assignable to `Integer[2]`".

**Comment by gavinking** [comment] 2015-10-13 16:56
Is this a dupe of non-bug https://github.com/ceylon/ceylon-model/issues/6?

**Comment by gavinking** [comment] 2015-10-13 17:00
Oh no, unlike ceylon/ceylon-model#6 it seems to be an actual bug. But like ceylon/ceylon-model#6 this is nothing to do with the typechecker itself, AFAICT, and is just a minor bug in `TypePrinter` in `ceylon-model`.

**Comment by jvasileff** [comment] 2015-10-13 17:02
Sounds right

**Comment by gavinking** [comment] 2015-10-16 15:58
Fixed.

**Closed** 2015-10-16 15:57 UTC
Labels: bug
